version: "3.7"


services:
  table-db:
    image: postgres:16
    container_name: table-db
    user: postgres
    #    Uncomment for persistent storage
    #    volumes:
    #      - ./data/db:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_DB=tabledb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "tabledb" ]
      interval: 10s
      timeout: 120s
      retries: 10
  table-ui:
    build:
      dockerfile: Dockerfile
      context: table-ui
    image: table-ui:latest
    ports:
      - "4000:80"
    depends_on:
      - table-backend
  table-backend:
    build:
      dockerfile: Dockerfile
      context: table-backend
    image: table-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://table-db:5432/tabledb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      table-db:
        condition: service_healthy
